[package]
name = "art_112144"
version = "0.1.0"
edition = "2021"
description = "My first crate, just an example, a useless crate that is just an example."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
