name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_collections:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./collections/std_collections

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -vv
    - name: Clippy
      run: cargo clippy
    - name: Run
      run: cargo run -vv
